name: caller
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
      - '1.develop-*'
  workflow_dispatch:
 
defaults:
  run:
    shell: bash

  # Note: If 'strategy.matrix' is used, it does not give a pipeline view for each IMS component.
  # Therefore, instead of using 'strategy.matrix', invoke the reusable workflow for each IMP comonent.
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up environment variables
        run: |
          TZ=Asia/Kolkata
          COMMIT_SHA=${{ github.sha }}
          REPO_NAME=${{ github.repository }}
          BRANCH_NAME=${{ github.ref }}
          CURRENT_TIME=$(date +%T) >> $GITHUB_ENV
          sed 's/\${COMMIT_SHA}/${COMMIT_SHA}/g' config/build-version.yaml > config/build-version.yaml
          sed -i 's/\${REPO_NAME}/${REPO_NAME}/g' config/build-version.yaml
          sed -i 's/\${BRANCH_NAME}/${BRANCH_NAME}/g' config/build-version.yaml
          sed -i 's/\${CURRENT_TIME}/${CURRENT_TIME}/g' config/build-version.yaml
          

      - name: Run
        run: cat config/build-version.yaml
