name: caller
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
      - '1.develop-*'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

  # Note: If 'strategy.matrix' is used, it does not give a pipeline view for each IMS component.
  # Therefore, instead of using 'strategy.matrix', invoke the reusable workflow for each IMP comonent.
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up environment variables
        run: |
          echo "TZ=Asia/Kolkata" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV
          echo "CURRENT_TIME=$(date +%T)" >> $GITHUB_ENV
          echo "HELM_DIR_PATH=mgmtplane/apiconnector/helm-chart" >> $GITHUB_ENV
          
      - name: Run
        run: |
          cat ${HELM_DIR_PATH}/build-version.yaml

      - name: Populate Build Info File
        run: |
          echo ${HELM_DIR_PATH}
          sed 's/\${COMMIT_SHA}/${COMMIT_SHA}/g' ${HELM_DIR_PATH}/build-version.yaml > ${HELM_DIR_PATH}/build-version.yaml
          sed -i 's/\${REPO_NAME}/${REPO_NAME}/g' ${HELM_DIR_PATH}/build-version.yaml
          sed -i 's/\${BRANCH_NAME}/${BRANCH_NAME}/g' ${HELM_DIR_PATH}/build-version.yaml
          sed -i 's/\${CURRENT_TIME}/${CURRENT_TIME}/g' ${HELM_DIR_PATH}/build-version.yaml
          cat ${HELM_DIR_PATH}/build-version.yaml
          
          #mv ${HELM_DIR_PATH}/build-version.yaml ${COMPONENT_BASE_DIR}/helm/templates/build-version.yaml

          

      - name: Run post
        run: |
          cat ${HELM_DIR_PATH}/build-version.yaml
