name: ENV TEST
on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash
 
jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.myid.outputs.test}}
    steps:

      - name: env-setup
        id: myid
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
          
  validate:
    runs-on: ubuntu-latest
    env:
      OUTPUT1: ${{needs.create.outputs.output1}}
    steps:
      - name: env-val
        run: echo $OUTPUT1
        
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
          
          
 # use:
 #   uses: gitwit-mistry/gha-poc/.github/workflows/cp.yml@main
 #   with:
  #    timestamp: ${{ needs.create.outputs.output1 }}
  #  secrets: inherit
