# This is a basic workflow to help you get started with Actions

name: CI-ondemand

# Controls when the workflow will run
on:
 # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select existing tag'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
            
  on-demand-builds-tag:
     if: "${{ github.event.inputs.tag != '' }}"
     name: Create Release for on-demand
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: GitHub Tag (with tags filter)
         uses: ncipollo/release-action@v1
         with:
           tag: ${{ github.event.inputs.tag }}"
           makeLatest: true
           token: ${{ secrets.PAT }}
         
     
     
     
    

