name: IMAGE BUILD
on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash
 
jobs:
  build_deps:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout
        uses: actions/checkout@v3
              
      - name: env-setup
        run: |
            mkdir test_dir
            echo "Hello" > test_dir/test.txt
          
      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            test_dir/test.txt
            
  build_deps_download:
    runs-on: ubuntu-latest
    needs: build_deps
    steps:
          
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          
      - name: upload build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: |
            test_dir/test.txt
            
      - name: env-setup-download
        run: |
            ls -l
            tree

