name: IMAGE BUILD
on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash
 
jobs:
  build_deps:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout
        uses: actions/checkout@v3
              
      - name: env-setup
        run: |
           echo "UID=$UID GID=$GID"
           docker build -t myimage:v1 .
           docker images
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}
          
      - name: env-setup
        uses: docker://myimage:v1
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}

