name: Manual and PR Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      release_no:
        description: 'A custom input variable'
        required: false
        default: 'default-value'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_NO: ${{ inputs.release_no }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and print variable
        id: release-no
        run: |
          echo "RELEASE_NO=develop" >> $GITHUB_ENV

    outputs:
      release_no: ${{steps.release-no.outputs.RELEASE_NO}}

   
  validate:
    runs-on: ubuntu-latest
    needs: build
    env:
      RELEASE_NO: ${{ needs.build-service.outputs.release_no }}
    steps:

    - name: Check and print variable
      run: |
          echo "${RELEASE_NO}"
    
    
          
