name: Manual and PR Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      custom-variable:
        description: 'A custom input variable'
        required: false
        default: 'default-value'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_NO: ${{ inputs.release_no }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and print variable
        run: |
          if [ -z "${RELEASE_NO}" ]; then
            echo "${RELEASE_NO}"
          else
            echo "develop"
          fi
