name: Manual and PR Workflow 

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      custom-variable:
        description: 'A custom input variable'
        required: false
        default: 'default-value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print custom variable
        run: echo "Custom variable:${{ github.event.inputs.custom-variable }}"

      - name: Run tests
        run: npm test
